### ISSUE TITLE
Please translate it in English

### ISSUE THREAD

**Issue by TheBalkanDev** [TATCHAN0825/blackjack#2]
I don’t can understand the README.md

**Comment by PJZ9n** [comment]
You can use Google
https://translate.google.com/translate?hl=&sl=ja&tl=en&u=https%3A%2F%2Fgithub.com%2FTATCHAN0825%2Fblackjack%2Fblob%2Fmaster%2FREADME.md

**Comment by TATCHAN0825** [comment]
https://github.com/TATCHAN0825/blackjack/commit/c8e50162d11560873cb07b9f0060c90e173aac1d
